### ISSUE TITLE
"Unexpected element BlockGroup" when processing ffmpeg webm output 

### ISSUE THREAD

**Issue by skerit** [acolwell/mse-tools#1]
Hi,

I'm converting some h264 files to WebM on-the-fly, using ffmpeg.
I'm piping the data into the `mse_webm_remuxer` binary. Most of the time it does a fine job, but on some files it throws this error:

```
2015/05/16 01:38:19 OnBinary() : Unexpected element BlockGroup                                       
2015/05/16 01:38:19 Parser error      
```

I only see 1 reference to BlockGroup in the code, but don't really know what's up with that.
Is there a way to fix this?

Maybe on FFMPEG's side? Maybe in the remuxer, so it can just skip this error?

**Comment by acolwell** [comment]
Sorry. I didn't see this until just now. Could you please post a sample webm stream that exhibits this problem. Please use creative commons or public domain content if possible.

**Comment by jamesruan** [comment]
I also come across this problem. It is quite easy to reproduce:

```
$ ffmpeg -i tears_of_steel_1080p.webm -vf scale=-1:320 -c:v libvpx-vp9 -keyint_min 150 -g 150 -tile-columns 4 -frame-parallel 1 -b:a 96000 -c:a opus ~/webm/out/sample.webm
$ ./mse_webm_remuxer ~/webm/out/sample.webm out.webm
2016/11/14 13:01:55 OnBinary() : Unexpected element BlockGroup
2016/11/14 13:01:55 Parser error

```

The video sample is downloaded from [https://media.xiph.org/tearsofsteel/tears_of_steel_1080p.webm](url)

**Comment by acolwell** [comment]
I've reproduced the problem locally and will try to get a fix out sometime this week.

**Comment by jamesruan** [comment]
Take your time.

For now I don't understand WHAT this 'remuxer' fixes. Maybe its not useful for ffmpeg generated webm.

**Comment by acolwell** [comment]
I believe this should be fixed now.
