### ISSUE TITLE
panic: rawTimecode is too big

### ISSUE THREAD

**Issue by d3im** [acolwell/mse-tools#7]
Hi, please could someone explain what is rawTimecode?
What is the source of problem and how could be this fixed?
Thanks in advance :-)

**Comment by acolwell** [comment]
The "rawTimecode" referenced in this error message refers to the timecode that is being placed into a SimpleBlock header(https://matroska.org/technical/specs/index.html#simpleblock_structure) This timecode value is relative to the cluster timecode and is a signed 16-bit number. This puts a constraint on how long clusters are allowed to be. 

It is hard to know what is exactly happening without a sample file, but if I were to guess, I bet that the keyframes in your video are too far apart. The remuxer is trying to ensure that clusters always start with a keyframe and if the keyframes are too far apart then you may end up with "rawTimecode" values that are larger than 32767 (ie the max allowed value for a single cluster). If your files have a typical timescale of 1000000 like the example file you sent in the other bug, then I'm guessing your keyframes are more than 32.767 seconds apart.

**Comment by d3im** [comment]
It's strange, because this should be set by ffmpeg parameter g and it was set to 250, so for 25 fps it gives me 10 seconds max. Didn't code much videos so far, but this error gives me some short videos at 30 fps with g set to 250 also. But the higher fps, with same g could give less interval between keyframes.
Here is link to error output and dump of one problematic video. Hope it could help, and thank You for response!
http://www.fileconvoy.com/dfl.php?id=g453607d2020ac36b100006922043a8fe28eb104d23

**Comment by acolwell** [comment]
Nothing obvious is jumping out at me from these logs. It would be easier to debug if I had an example webm file that you are trying to remux. It looks like the video keyframes are about 10sec apart most of the time so I'm not sure why this is happening. 

I suspect something is happening that is preventing this code(https://github.com/acolwell/mse-tools/blob/master/mse_webm_remuxer/mse_webm_remuxer.go#L553) from triggering the creation of a new cluster.

**Comment by d3im** [comment]
I've succeeded in converting some neutral video with this error:
http://www.fileconvoy.com/dfl.php?id=g5126aee6f889d94410000693541a0bc82b327a4993
Weird is 29.97 fps was OK but the same at 30 fps wasn't.
Original video:
https://pixabay.com/en/videos/space-ship-rocket-launch-nasa-3/

**Comment by d3im** [comment]
Seems everything >= 30fps gives the error.

**Comment by acolwell** [comment]
I believe this should be fixed now. The original code was trying to always ensure that a cluster starts with an audio block. Unfortunately that can't always happen if an audio block spans multiple video frames. In the past with Vorbis and content that was <= 30fps this didn't tend to come up, but using Opus and video > 30fps make this situation much more likely.  

If my fix doesn't fix the issue, go ahead and reopen this bug and provide a new example file that the new code.
